# Configuration for Rasa NLU.
## https://huggingface.co/Davlan/bert-base-multilingual-cased-finetuned-swahili
## https://huggingface.co/Davlan/xlm-roberta-base-finetuned-swahili
# https://rasa.com/docs/rasa/nlu/components/
language: rw

pipeline:
#   https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  - name: SpacyNLP
    model: "xx_ent_wiki_sm"
    case_sensitive: false
  - name: "SpacyEntityExtractor"
    dimensions: ["GPE"]
# https://rasa.com/docs/rasa/core/policies/  Configuration for Rasa Core
policies:
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: linear_norm
  - name: RulePolicy
